name: Terraform Plan and Apply

on:
  push:
    branches:
      - main # Adjust this to the branch you want to trigger the action on

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Run Terraform Plan and Apply
        run: |
          ./terraform_plan_apply.sh
        env:
          TF_ACTION: "true" # Enable non-interactive mode for Terraform (optional)
          AWS_REGION: "eu-central-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_STAG_CRED_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_STAG_CRED_SECRET }}